name: Deploy Storybook on Staging

on:
  workflow_dispatch:

jobs:
  create-staging-files:
    name: Creating Staging Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create staging folder
        run: mkdir staging
        
      - name: Copy files to staging
        run: cp -r -v ./packages/docs/.storybook/ ./staging/; cp -r -v ./packages/docs/src/ ./staging/; cp -v ./packages/docs/package.json ./staging/
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@guizioliveira'
      
      - name: Install Dependencies
        working-directory: ./staging/
        run: npm install
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      
      - name: Build Storybook
        working-directory: ./staging/
        run: npm run build
        env:
          TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TURBO_TEAM: guizioliveira
      
      - name: Remove staging folder
        run: sudo rm -r staging
