name: Release and Deploy Storybook

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-packages:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@guizioliveira'

      - name: Install Dependencies
        run: npm ci
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: Build Packages
        run: npm run build
        env:
          TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TURBO_TEAM: guizioliveira

  release-packages:
    name: Publish to NPM
    needs: build-packages
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@guizioliveira'

      - name: Install Dependencies
        run: npm ci
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: Publish by changesets changes
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  storybook-deploy:
    name: Storybook Deploy
    runs-on: ubuntu-latest
    needs: build-packages
    steps:
      - name: Storybook Deployment
        working-directory: ./packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}