name: Deploy Storybook on Staging

on:
  workflow_dispatch:

jobs:
  create-staging-files:
    name: Creating Staging Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create staging folder
        run: mkdir staging
        
      - name: Copy files to staging
        run: cp -r .\packages\docs\.storybook ./staging | cp -r .\packages\docs\src ./staging | cp ./packages/docs/package.json ./staging

        
      - name: Remove staging folder
        run: sudo rm -r staging
