name: NPM Release & Deploy

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-and-release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@guizioliveira'

      - name: Install Dependencies
        run: npm ci
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: Build All Application
        run: npm run build:packages
        env:
          TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TURBO_TEAM: guizioliveira

      - name: Publish by changesets changes
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  storybook-deploy-staging:
    name: Storybook deploy / Staging
    runs-on: ubuntu-latest
    needs: build-and-release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy files to staging
        run: mkdir staging; cp -r -v ./packages/docs/.storybook/ ./staging/; cp -r -v ./packages/docs/src/ ./staging/; cp -v ./packages/docs/package.json ./staging/
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@guizioliveira'
      
      - name: Install Dependencies
        working-directory: ./staging/
        run: npm i --legacy-peer-deps
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      
      - name: Build Storybook
        working-directory: ./staging/
        run: npm run build
        env:
          TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TURBO_TEAM: guizioliveira

      - name: Storybook Deployment / Github Pages
        working-directory: ./staging/
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
